config/routes.rb
Rails.application.routes.draw do
  get '/' => 'teams#index'


  resources :players, only: [:new, :create, :index]

  resources :teams do 
    resources :players, shallow: true #index, create, new
  end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/player.rb
class Player < ApplicationRecord
  belongs_to :team
end

app/models/team.rb
class Team < ApplicationRecord
    has_many :players
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  before_action :set_player, only: %i[ show edit update destroy ]

  # GET /players or /players.json
  def index
    if params[:team_id]
      @team = Team.find_by(id: params[:team_id])
      @players = @team.players
      render :team_players
    else
      @players = Player.all
    end
  end

  # GET /players/1 or /players/1.json
  def show
  end

  # GET /players/new
  def new
    if params[:team_id]
      @team = Team.find_by(id: params[:team_id])
      @player = @team.players.new
      render :team_new
    else
      @player = Player.new
      @teams = Team.all
    end
  end

  # GET /players/1/edit
  def edit
  end

  # POST /players or /players.json
  def create
    if params[:team_id]
      @team = Team.find_by(id: params[:team_id])
      @player = @team.players.new(player_params)
      if @team.save
        redirect_to @team
      else
        render :team_new
      end
    else
      @player = Player.new(player_params)
      respond_to do |format|
        if @player.save
          format.html { redirect_to player_url(@player), notice: "Player was successfully created." }
          format.json { render :show, status: :created, location: @player }
        else
          format.html { render :new, status: :unprocessable_entity }
          format.json { render json: @player.errors, status: :unprocessable_entity }
        end
      end
    end
  end

  # PATCH/PUT /players/1 or /players/1.json
  def update
    respond_to do |format|
      if @player.update(player_params)
        format.html { redirect_to player_url(@player), notice: "Player was successfully updated." }
        format.json { render :show, status: :ok, location: @player }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /players/1 or /players/1.json
  def destroy
    @player.destroy

    respond_to do |format|
      format.html { redirect_to players_url, notice: "Player was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_player
      @player = Player.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def player_params
      params.require(:player).permit(:name, :team_id)
    end
end

app/controllers/teams_controller.rb
class TeamsController < ApplicationController
  before_action :set_team, only: %i[ show edit update destroy ]

  # GET /teams or /teams.json
  def index
    @teams = Team.all
  end

  # GET /teams/1 or /teams/1.json
  def show
  end

  # GET /teams/new
  def new
    @team = Team.new
  end

  # GET /teams/1/edit
  def edit
  end

  # POST /teams or /teams.json
  def create
    @team = Team.new(team_params)

    respond_to do |format|
      if @team.save
        format.html { redirect_to team_url(@team), notice: "Team was successfully created." }
        format.json { render :show, status: :created, location: @team }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @team.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /teams/1 or /teams/1.json
  def update
    respond_to do |format|
      if @team.update(team_params)
        format.html { redirect_to team_url(@team), notice: "Team was successfully updated." }
        format.json { render :show, status: :ok, location: @team }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @team.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /teams/1 or /teams/1.json
  def destroy
    @team.destroy

    respond_to do |format|
      format.html { redirect_to teams_url, notice: "Team was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_team
      @team = Team.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def team_params
      params.require(:team).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PlayerTeam</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%# <%= link_to "Workers Tasks", '/' %> 
    <%= link_to "Teams", teams_path %> | 
    <%= link_to "Players", players_path %>
    <%= yield %>
  </body>
</html>

app/views/players/_form.html.erb
<%= form_with(model: player) do |form| %>
  <% if player.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(player.errors.count, "error") %> prohibited this player from being saved:</h2>

      <ul>
        <% player.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :team_id, style: "display: block" %>

    <%= form.collection_select :team_id, @teams, :id, :name %>

    <%# <%= form.text_field :team_id %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/players/_player.html.erb
<div id="<%= dom_id player %>">
  <p>
    <strong>Name:</strong>
    <%= player.name %>
  </p>

  <p>
    <strong>Team:</strong>
    <%= player.team.name %>
  </p>

</div>

app/views/players/_team_form.html.erb
<%= form_with(model: player, url: team_players_path) do |form| %>
  <% if player.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(player.errors.count, "error") %> prohibited this player from being saved:</h2>

      <ul>
        <% player.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/players/edit.html.erb
<h1>Editing player</h1>

<%= render "form", player: @player %>

<br>

<div>
  <%= link_to "Show this player", @player %> |
  <%= link_to "Back to players", players_path %>
</div>

app/views/players/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Players</h1>

<div id="players">
  <% @players.each do |player| %>
    <%= render player %>
    <p>
      <%= link_to "Show this player", player %>
    </p>
  <% end %>
</div>

<%= link_to "New player", new_player_path %>

app/views/players/new.html.erb
<h1>New player</h1>

<%= render "form", player: @player %>

<br>

<div>
  <%= link_to "Back to players", players_path %>
</div>

app/views/players/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @player %>

<div>
  <%= link_to "Edit this player", edit_player_path(@player) %> |
  <%= link_to "Back to players", players_path %>

  <%= button_to "Destroy this player", @player, method: :delete %>
</div>

app/views/players/team_new.html.erb
<h1>New player</h1>

<%= render "team_form", player: @player  %>

<br>

<div>
  <%= link_to "Back to players", players_path %>
</div>

app/views/players/team_players.html.erb
<p style="color: green"><%= notice %></p>

<h1>Players</h1>

<div id="players">
  <% @players.each do |player| %>
    <%= render player %>
    <p>
      <%= link_to "Show this player", player %>
    </p>
  <% end %>
</div>